apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service
  namespace: staging
  labels:
    app: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  namespaceSelector:
    matchNames:
      - staging
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      targetPort: 8000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: student-service
  namespace: staging
  labels:
    app: student-service
spec:
  selector:
    matchLabels:
      app: student-service
  namespaceSelector:
    matchNames:
      - staging
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      targetPort: 8000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lecturer-service
  namespace: staging
  labels:
    app: lecturer-service
spec:
  selector:
    matchLabels:
      app: lecturer-service
  namespaceSelector:
    matchNames:
      - staging
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      targetPort: 8000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: course-service
  namespace: staging
  labels:
    app: course-service
spec:
  selector:
    matchLabels:
      app: course-service
  namespaceSelector:
    matchNames:
      - staging
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      targetPort: 8000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: enrollment-service
  namespace: staging
  labels:
    app: enrollment-service
spec:
  selector:
    matchLabels:
      app: enrollment-service
  namespaceSelector:
    matchNames:
      - staging
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      targetPort: 8000